---
efiBootLoader: grub
kernel: /boot/vmlinuz
img: /boot/initrd.img
timeout: "5"
bootloaderEntryName: "Master Penguin Linux"
kernelLine: ", with Master Penguin"
fallbackKernelLine: ", with Master Penguin (recovery)"
grubInstall: grub-install
grubMkconfig: grub-mkconfig
grubCfg: /boot/grub/grub.cfg
efiBootloaderId: master-penguin
installEFIFallback: true
